### ISSUE TITLE
Planned changes

### ISSUE THREAD

**Issue by ProditorMagnus** [ProditorMagnus/Ageless-for-1-14#1]
Certain
- [ ] a

1.20
- [ ] https://github.com/wesnoth/wesnoth/pull/9979 use and add unit test
- [ ] events to abilities only if https://github.com/wesnoth/wesnoth/pull/10812#issuecomment-3702479627 is solved https://github.com/wesnoth/wesnoth/issues/10819
- [ ] review if some new core monster units or their images are useful

Maybe
- [ ] try add https://github.com/Refumee/Refumees_Saurian_Pack only deep saurians - too much bother for one faction for one user
- [ ] move all ability and event definitions from units to data
- [ ] think of https://github.com/ProditorMagnus/WML_tree_tools/issues/1
- [ ] check if some ideas from FL summon should go to EoMa
- [ ] consider if EFM hex should use RE way cripple
- [ ] consider if khthon with ranged attack should always use vector to defend when vector conditions are satisfied
- [ ] https://forums.wesnoth.org/viewtopic.php?p=648625#p648625 dawnbringer

Postponed
- [ ] Move deep elf trample to macro and check if it adds fight and kill xp
- [ ] consider lowering equestrian knight movement and increasing pierce resist
- [ ] shifter can gain/lose hp when it shouldnt https://github.com/wesnoth/wesnoth/pull/8147

Not planned
- [ ] Anakes animation https://forums.wesnoth.org/viewtopic.php?p=628626#p628626
- [ ] use https://github.com/wesnoth/wesnoth/blob/master/data/multiplayer/eras.lua#L5 way
- [ ] RE is missing recruits in heroes era
- [ ] alter AE_RHY_WEAPON_SPECIAL_BLOODMAGIC to have useful description
- [ ] Check power level of windsong https://forums.wesnoth.org/viewtopic.php?p=628330#p628330
- [ ] brungar tamer summon wolf caused oos in creep war
- [ ] possible new era https://forums.wesnoth.org/viewtopic.php?f=19&t=44528
- [ ] review images by tommy2teeth #25 there were nonimage changes
- [ ] EoZ says something wrong with MiE faction with cornur/gnoll/minotaur, plague not working - seems intentional, but add trait? -- bring in MiE changes
- [ ] https://forums.wesnoth.org/viewtopic.php?p=631029#p631029 deep elf update
- [ ] https://forums.wesnoth.org/viewtopic.php?p=634757#p634757 EFM feedback

**Comment by ProditorMagnus** [comment]
Done 4.40
- [x] reload harpy, verify indentation is fixed
- [x] ensure wml_tree_tools catches https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/units/FL_units/altaris/Light_Scout.cfg#L15

Done 4.39
- [x] auto_sort=none or refactor ZWS sorting, for example `Current:
Random not Defaultlike
Random Balanced
Random
Random AE
For sorting:
Random (not Defaultlike)
Random (only Balanced)
Random (with Default)
Random AE and all other groups`
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/commit/1864a0bd41c4ffc97adeaa04419575ca8118006e#diff-ef71f0c5ab1fde99359e9eee24409abb66b5b8b69d0a0a4dfffbfe6460c88ec8 add icons back
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/commit/85e28903f448352bab1c4cb7c8a9e1fb15271e5e
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/commit/d61983b35bb59b8c4d4c94c2c22b5857a5127b96
- [x] smaller EoMa faction images replacement rule https://github.com/ProditorMagnus/Ageless-Resources-1-14/commit/c3065fd4ed5f7b22f6b486ab32465c795ab72384

Done 4.38
- [x] some harpy units have no image, 'dukeofthenight/duke-of-the-night-idle1.png'
- [x] shifter Dd^Dr mapping for goat doesnt work since boar already claims D
- [x] https://github.com/wesnoth/wesnoth/commit/f3addad107f5d66c1779ee39e4dcc39be2424430 https://github.com/ProditorMagnus/Ageless-for-1-14/blob/35367692a6938e0e138f232955e38d48115f4ff8/data/overrides.cfg#L28 can ifver 1.19.13 to empty
- [x] verify AE_myh_Battle_Wizard and AE_myh_Great_Wizard do not break compatibility. consider these unit types as deprecated: AE_myh_Spitting_Cobra, AE_myh_King_Cobra, AE_myh_Sea_Snake, AE_myh_Sandskipper, AE_myh_Great_Wizard, AE_myh_Wolf, AE_myh_Dire_Wolf. Also AE_ext_drake_Adventurer
- [x] AE_ext_drake_Ranger AE_ext_drake_Adventurer
- [x] verify ee outlaw new unit images

Done 4.37
- [x] The EOMA factions seem bugged in RPG. They display question marks instead of units. - Looks like bug in my EoMa update script.
- [x] https://github.com/inferno8/wesnoth-Era_of_Magic/issues/70
- [x] https://github.com/inferno8/wesnoth-Era_of_Magic/issues/69
- [x] hast to spear/pike
- [x] kthlon enthrallment make it work only on units of the same and lower level than the kthlon that attacks so for example lvl1 kthlon (let's say ram) can only thrall lvl1 and lvl0 units but not lvl2+
- [x] (ELE - Horned Skeletons) Skeletal Guard (and Fortress) have a weak "bone javelin" attack Which somehow marked as melee.
- [x] enable AoA heroes and rpg

Done 4.36
- [x] try https://github.com/inferno8/wesnoth-To_Lands_Unknown/pull/90/files
- [x] look for [/attack]    [/attack]
- [x] "while its its night"
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/pull/46
- [x] review correctness of [filter_self], most should be changed to [filter] even though [filter_self] works the same for single target abilities https://github.com/wesnoth/wesnoth/issues/9240
- [x] remove defense_weight=0.1
- [x] validate chs elementals, ee drakes is playable
- [x] icon for artillery range & insects damage type
- [x] bmr icons, all images under wrong folder
- [x] test "$(relative_dir(loc($unit.x,$unit.y), loc($second_unit.x,$second_unit.y)))" as knockback_direction
- [x] AoA stuff, such as renaming types+files, rpg faction
- [x] validate new units can move, wisp mother

Done 4.35
- [x] consider race of https://github.com/ProditorMagnus/Ageless-for-1-14/blob/7e0a76460adefca92cff541a2196c5fc7f4099e8/data/MiE_data/abilities.cfg#L25 dwarf could go to substring matchformula="contains_string(race, 'dwar')", but brungar and no custom dwarf races - decided to not use substring, but change vampirism to exclude only monsters

Done 4.34
- [x] migrate AE_efm_trample_event to low priority die event
- [x] add conversion rule to change AE_FL_summon_golem to AE_mag_summon, preferably while keeping EoMa in help -- or change manually, it is not getting updates anyways -- ability=AE_mag_summon ability_id_active=AE_mag_summon conversion rule add all FL ids

Done 4.33
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/blob/878c9851531a4b7d4918ce4787fa7f6a765b8ca3/data/EoC_data/abilities.cfg#L180
- [x] Conflicting files in binary_path: 'C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.16\data\add-ons\Ageless_Resources\general\images\factions\EoMa-faction-barbarians.png' and 'C:\Users\USER\OneDrive\Documents\My Games\Wesnoth1.16\data\add-ons\Era_of_Magic_Resources\images\factions\EoMa-faction-barbarians.png'
- [x] when updating resources change filename back https://github.com/ProditorMagnus/Ageless-for-1-14/commit/f3f1eef7ac834a566b222cfea522703bab1e57f8 https://github.com/ProditorMagnus/Ageless-Resources-1-14/commit/759a249b66fa73a43d1f87eefde38a49fc993651
- [x] move RE and FL images to resources
- [x] remove Ageless_Resources\general\images\units\wargs\moon-blade readme

Done 4.32
- [x] https://forums.wesnoth.org/viewtopic.php?p=684474#p684474
- [x] error display: could not open image 'projectiles/icemissile-nw-2.png'
- [x] "Descend into darkness" does not work, but would be too powerful if it did work

Done 4.31
- [x] fix FL illusions
- [x] consider orocia exclude AE_stf_triththa_Ballista, AE_arc_phantom_Vapor
- [x] check AE_myh_UNUSED 
- [x] altaris golem summoning probably doesnt work
- [x] ABILITY_AE_MAG_MOUNTAINAMBUSHSTERHEAL looks like wrong replacement
- [x] AE_mrc_triplestrike_event id on 2 events
- [x] use EoMa bleed instead of nordhris
- [x] rpg disable advancement to physical endurance demon
- [x] mrc graverobber - at most 20hp per kill, in rpg not allowed to violate max hp
- [x] ele consume violates max hp
- [x] meganerie typo
- [x] union era needs to load resource

Done 4.30
- [x] ensure https://github.com/inferno8/wesnoth-Era_of_Magic/issues/30 is solved, especially about kill xp
- [x] blacklist from orocia AE_mag_Forest_Spirit AE_mag_Swamp_Spirit
- [x] think of #2
- [x] review if some EoMa era level events need to be loaded https://github.com/inferno8/wesnoth-Era_of_Magic/pull/46
- [x] special_id_active doesnt work

Done 4.29
- [x] https://github.com/inferno8/wesnoth-Era_of_Magic/issues/29
- [x] change https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/data/RE_data/abilities.cfg#L112 description/name to not confuse with mainline

Done 4.28
- [x] regenerate units and factions for 1.15.3+
- [x] #27 use resource for era events
- [x] AE_myh_Nailers should have ability to mention no zoc

Done 4.27
- [x] revert https://github.com/ProditorMagnus/Ageless-for-1-14/commit/e12a49282fc598f3a7c8dd702dcb304a8daa3026#diff-ae576e16b81d2a7a71afe5253f60ecc2 file
- [x] move sneaky tentacle to level 1
- [x] Dancer and Harlot are not recruitable in Mercenaries Era with Ageless Heroes
- [x] remove extra attack from Um
- [x] use unit placed or similar for longshot menu setup - removed longshot at all

Done 4.26
- [x] use union era only #ifndef \_\_WMLUNITS__
- [x] hide union eras from wmlunits - need separate processed cfg file for them
- [x] no need to use preprocessed version anymore with timeout 100sec
- [x] welkin luna protector level 2 has strange resists - fix negative, but intentional that 17
- [x] update dune https://forums.wesnoth.org/viewtopic.php?p=650058#p650058
- [x] hex regression #18

Done 4.25
- [x] use special_active instead of special for filtering attacks
- [x] ELE arcane aura does not work as described - side filter and affect self
- [x] change AE_ele_banner to not be cumulative with itself
- [x] ele centaur Fighter is too cost efficient
- [x] add hide_help to AE_mag_bug_3827
- [x] remove marksman from wingless dragon - weakened further
- [x] https://forums.wesnoth.org/viewtopic.php?f=23&t=50118
- [x] there is no reason to worry about corrupting ABILITY_CURES and such
- [x] fallen fighter line too strong
- [x] add https://github.com/ProditorMagnus/Ageless-Resources-1-14/commit/ac30ce94809cd9ec27cedaed030b439a873cd489 or release resources
- [x] write that eoc demon immune to plague
- [x] safely move /units/wood_warriors/tongue.png to attacks folder
- [x] remove units with max level <2 from random leader lists

Done 4.23:
- [x] SPECIAL_NOTES_PRECISION can be misleading
- [x] https://github.com/ProditorMagnus/Ageless-for-1-14/blob/master/units/EoMa_units/Dark_Blood_Alliance/Wyvern.cfg#L33 or import EoMa
- [x] units with 444 and 555 hp
- [x] ELE fallen tamer and EoMa Gods hp bar is too far

Done 4.22:
- [x] 20181231 13:21:53 error display: could not open image 'attacks/sunburst.png'
- [x] fix ELE consume and holy
- [x] fix EotF reef movement
- [x] could not open image units/ME_units/highlanders/d2-amputator.cfg:            image="projectiles/dagger.png" 
- [x] Here to note what I suppose is a bug in the Archaic Faction "Phantoms." They have a unit on their recruit list called "Vapor" which costs 5 gold and proportedly disappears when attacked by an enemy unit. However, this "disappearing" function only appears to be working on the unit "feather dancer," my other units still live after being hit by enemy attacks. 
- [x] EoZ says something wrong with MiE faction with cornur/gnoll/minotaur, plague not working
- [x] units/orcs/shaman-tan.png projectiles/viking-missile-ne.png items/ballista-lavinian-archuballistarius.png units/undead-skeletal-horned/skeletal-mage-ridedr.png portraits/creatures/giant-rat.png units/undead-skeletal-horned/skeletal-maistress.png items/boat-marauder-sailor.png windsong/savant.png units/slavers/coutesan.png units/ukains/seals/pack-seal.png units/human-arendians/archer-attack-ranged-e-7.png not found
- [x] <[21:17] EIder> goblin kamikaze zombie doesnt die when using kamikaze attack - upstream
- [x] wingless dragon can move on unwalkable
- [x] Starshower gets too much hp when advancing
- [x] check for 0 mp for AE_agl_knockback
- [x] sculpt in rpg
- [x] union eras
```
wmlindent: "./units/EFM_units/Freemen/e3_Sheik.cfg". line 127: end of file with indent nonzero.
wmlindent: "./units/EFM_units/Freemen/e1_Wanderer.cfg". line 122: end of file with indent nonzero.
wmlindent: "./units/EFM_units/Freemen/e2_Nomad.cfg". line 122: end of file with indent nonzero.
```

Done 4.21:
- [x] 20180619 03:53:18 error display: could not open image 'units/holyorder/scholarpng'
- [x] 20180628 17:51:38 error display: could not open image 'units/fiends/ifreetmaster.png'
- [x] Include EoMa resources binary path
- [x] 20180630 00:37:15 warning config: Terrain 'Xt' has evaluated to 100 (cost), which is more than 99; resetting to 99.
- [x] EoC dark legion drone is too cheap 11 -> 13
- [x] 20180619 11:14:37 error display: could not open image 'units/slavers/miners.png'
- [x] 20180619 10:50:47 error display: could not open image 'units/primeval/leader-defend1.png'
- [x] AE_ELE_ABILITY_SHIELDWALL and advance are broken
- [x] <[14:54] *nelaima_*> skeleton banner and skeleton frontfighter attackonly doesnt work - https://github.com/wesnoth/wesnoth/issues/3324

Done 4.20:
- [x] Remove full changelogs from unsynced menu
- [x] Fix deadly strike Lua errors
- [x] Error: Era 'Ageless Heroes' faction 'AE_rhy_side_Undead' references non-existant unit id 'Bone Knight'!
- [x] Error: Era 'Ageless Heroes' faction 'AE_rhy_side_Dwarves' references non-existant unit id 'AE_rhy_dw_Fighter'!
- [x] Warning: No picture units/elementals/djinn.png for unit AE_chs_elementals_Djinn.
- [x] Warning: No picture /units/Brungar/Crystal_Master.png for unit AE_fut_brungar_Crystal_Master.
- [x] Remove MAGENTA_IS_THE_TEAM_COLOR
- [x] Add {TRAIT_ELEMENTAL} to AE_ext_monsters_Baby_Mudcrawler
- [x] Use [attacks] instead of [swarm] for Oathsworn, for this unit can allow +%
- [x] Consider adding workaround for https://github.com/wesnoth/wesnoth/issues/3135
- [x] Vilkai is not in any factions group
- [x] AE_efm_saga is broken
- [x] Remove frozen golem knockback
- [x] Add prefix to attack/defend only, change to disable
- [x] #3 
- [x] Use https://forums.wesnoth.org/viewtopic.php?p=628427#p628427
- [x] Handle https://forums.wesnoth.org/viewtopic.php?p=628111#p628111 - https://github.com/wesnoth/wesnoth/issues/3177
- [x] Add submerge for death baron
- [x] Reduce oracles summoner damage and cost
- [x] typo ./add-ons/Ageless_Era/data/RE_data/abilities_recruit_base.cfg: moves=$this_units.max_moves
- [x] remove EoMa images from resources
- [x] add random balanced
- [x] preprocessed version is loaded even when not in multiplayer
- [x] RE wolfguard +1 damage
- [x] fix some images: monsters spider, water snake, tsuwamono
