### ISSUE TITLE
List of changes to keep different from original

### ISSUE THREAD

**Issue by ProditorMagnus** [ProditorMagnus/Ageless-for-1-14#2]
### EoMa
- [x] Jinn not Jinni (for now, will consider changing)
- [ ] Remove Regen from Jinn, remove Jinn advance from DG, lower level 1 damage to 4-4, level 2 to 6-4, level 3 to 8-4 with +4 regen, lower damned shaman regen
- [ ] Limit Matriarch of Emptiness rpg power, in rpg limit of 50
- [ ] remove WEAPON_SPECIAL_AE_MAG_ATTACK_ONLY macro definition
- [ ] Remove ambush.cfg on merge
- [ ] Move special_notes & strings to text/
- [ ] look Master of Darkness power and fix description wording in EoMa
- [x] custom AMLA requirements before AMLA_DEFAULT

### Archaic
- [x] Mummy line being unbroken
- [x] Assimilation affects all living units
- [x] remove AE_ARCHAIC_ABILITY_ROCKHIDE, AE_ARCHAIC_ABILITY_DESERTSTALK, AE_ARCHAIC_ABILITY_AQUALUNG from Archaic_abilities.cfg

### To consider: EoMa:
- [ ] Too many EoMa units have regen
- [ ] Too many Destroyers units have awe
- [ ] Roc Rider might be too cost efficient
- [ ] Troll Warbanner seems much weaker then other line
- [ ] Dazzle is quite similar to hex, see if I it makes sense to handle them in same way
- [ ] Dark Assassin might be weaker than Great Hunter
- [ ] Increase Master of Darkness implosion damage
- [ ] Increase Matriarch of Frost damage
- [ ] Check toads, Toad Shaman line has strange resists
- [ ] Striding Machine is quite healthy
- [ ] Make hydra extra damage constant or nonrpg, or reduce scaling a lot: x+damage/y, also area effect scaling
- [ ] Use old Matriarch of Emptiness halo - octalot reports https://forums.wesnoth.org/viewtopic.php?p=629332#p629332

### Possibly outdated
- [x] Remove drain from Cyclops Lord (Ancient Cyclops), in return +2 damage and -2 damage for Cyclops Goliath eye
- [x] Unupgradable strikes: Prophet of Light dazzle; Child of Light and Mistress of Light lightstorm, with duplicate upgradable version; Air God storm, Wonderful Jinn ultra circle, Mystical Jinn ultra circle, Great Efreeti Destruction; Dark Warlord explosion; Swamp Mage and Chosen of Marsh damned flame; Master of Fire infernal wave, Omen line with upgradable alternative
- [x] AE_mag_Master_of_War too, but reconsider damned flame
- [x] Bone collector must be disabled in rpg/for leaders
- [x] disable awe in rpg
- [x] Sculpt must not affect leaders
- [x] EoMa 3.2.0: For RPG, please disable the Cyclops Necromancer's zombie-summoning.
- [x] Only Summoner can still use always hits in upgradable way, watch out
- [x] remove extra attack from Um

**Comment by stevecotton** [comment]
> Use old Matriarch of Emptiness halo - octalot reports https://forums.wesnoth.org/viewtopic.php?p=629332#p629332

The new halo in (EoMa 3.1.2 + EoMa Resources 1.1.0) is okay, it seems that something in the old halo (in Ageless 4.19) ends up with the transparent pixels being non-transparent in Wesnoth 1.14. IMO the new halo also looks much better than the old one.

**Comment by ProditorMagnus** [comment]
52c1eaf31722bb58046a1b459d4f29daa8d88487

**Comment by ProditorMagnus** [comment]
I like old rotating halo more though.

**Comment by ProditorMagnus** [comment]
f64a35c4372c5581bd6f2ae81bffa12d6667781b

**Comment by stevecotton** [comment]
EoMa 3.2.0: For RPG, please disable the Cyclops Necromancer's zombie-summoning.
